### ISSUE TITLE
In fact, centerInside is wrong

### ISSUE THREAD

**Issue by drakeet** [zuoweitan/CircleImageView#1]
I just modified your main layout with `android:src="@mipmap/ic_launcher"`,  `android:scaleType="centerInside"` and size to `128dp`: 

```java
<LinearLayout style="@style/circle_layout_style">

    <com.zuowei.circleimageview.CircleImageView
        android:src="@mipmap/ic_launcher"
        android:scaleType="centerCrop"
        android:layout_width="128dp"
        android:layout_height="128dp"
        style="@style/circle_style" />

    <TextView style="@style/cricle_text_style"
        android:text="centerCrop"/>

</LinearLayout>

<LinearLayout style="@style/circle_layout_style">

    <com.zuowei.circleimageview.CircleImageView
        android:src="@mipmap/ic_launcher"
        android:scaleType="centerInside"
        android:layout_width="128dp"
        android:layout_height="128dp"
        style="@style/circle_style" />

    <TextView style="@style/cricle_text_style"
        android:text="centerInside"/>

</LinearLayout>
```

And the result is wrong: 

![image](https://cloud.githubusercontent.com/assets/5214214/20744743/aabd0788-b718-11e6-9d62-18d582348b56.png)

**Comment by drakeet** [comment]
You can refer to the reply of https://github.com/hdodenhof/CircleImageView/issues/148 by @csNewscope 
> Could you please disable those limitations? There is no reason why only center crop is allowed. Think of images with an extra wide aspect ratio like a company logo. You have to use fitCenter(or centerInside) as scale type to get the full logo inside the circle.
Thanks in advance

According to my understanding, I think it should be this:

![image](https://cloud.githubusercontent.com/assets/5214214/20745580/f858a192-b71c-11e6-94da-a1987c1f099f.png)

**Comment by Byteschmiede** [comment]
agreed

**Comment by zuoweitan** [comment]
Thinks。

I don't think so.
"centerinside" works like this just like normal ImageView does.

If image size is smaller than the View attached to,image will only be centered on the View as it is.

but,if you expect that effect,you can try this(may be you should change the name to .java):
[CircleImageView.txt](https://github.com/zuoweitan/CircleImageView/files/638655/CircleImageView.txt)
